[workspace]
members = ["crates/marketdata-service", "crates/marketdata-types", "crates/feed-sim"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.rust]
unused_must_use = "warn"

[workspace.dependencies]
marketdata-types = { path = "crates/marketdata-types" }
feed-sim = { path = "crates/feed-sim" }

tokio = { version = "1", features = ["full"] }
dashmap = "6"
tonic = "0.12"
prost = "0.13"
tokio-stream = { version = "0.1", features = ["net"] }
tonic-build = "0.12"
protoc-bin-vendored = "3"
